# Generated by Django 6.0.4 on 2026-04-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hash_sync_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.config'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
